# Generated by Django 4.1.6 on 2023-03-01 10:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bixdata_app", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="MyModel",
        ),
    ]
