# Generated by Django 4.1.6 on 2023-03-01 10:29

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("bixdata_app", "0002_delete_mymodel"),
    ]

    operations = [
        migrations.CreateModel(
            name="MyModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "permissions": (
                    ("can_do_something", "Can do something"),
                    ("can_do_another_thing", "Can do another thing"),
                ),
            },
        ),
    ]
