# Generated by Django 4.1.6 on 2023-04-05 14:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bixdata_app", "0004_customuser"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="role",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
