# Generated by Django 4.1.6 on 2023-04-05 14:05

from django.db import migrations

def copy_user_data(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    CustomUser = apps.get_model('bixdata_app', 'CustomUser')
    for user in User.objects.all():
        CustomUser.objects.create(
            id=user.id,
            password=user.password,
            last_login=user.last_login,
            is_superuser=user.is_superuser,
            username=user.username,
            first_name=user.first_name,
            last_name=user.last_name,
            email=user.email,
            is_staff=user.is_staff,
            is_active=user.is_active,
            date_joined=user.date_joined,
        )

class Migration(migrations.Migration):

    dependencies = [
        ('bixdata_app', '0005_customuser_role'),
    ]

    operations = [
        migrations.RunPython(copy_user_data),
    ]

